<a href="https://colab.research.google.com/github/nupurmadaan04/Machine-learning-notebooks/blob/main/Data%20filling%20%2B%20Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd
import numpy as np

In [23]:
df = pd.read_csv("titanic.csv")

In [24]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [48]:
df['Age'].fillna(df['Age'].median(), inplace=True)
df['Fare'].fillna(df['Fare'].median(), inplace=True)
df['Cabin'].fillna(df['Cabin'].mode()[0],inplace=True)

/tmp/ipykernel_2444/3927764405.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)
/tmp/ipykernel_2444/3927764405.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Fare'].fillna(df['Fare'].median(), inplace=True)

In [45]:
# do backward filling , lower ones to upper
# ffill oppostie of this
df['Cabin'].fillna(method='bfill')

# axis = 1 , for columns df['Cabin'].fillna(method='bfill',axis=1)

/tmp/ipykernel_2444/206084947.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Cabin'].fillna(method='bfill')

0      B57 B59 B63 B66
1                  B45
2                  B45
3                  B45
4                  B45
            ...
413               C105
414               C105
415                NaN
416                NaN
417                NaN
Name: Cabin, Length: 418, dtype: object

In [51]:
from sklearn.impute import SimpleImputer

# Mean → for numerical data (no outliers ideally)
imputer_mean = SimpleImputer(strategy='mean')
df['Age'] = imputer_mean.fit_transform(df[['Age']])

# Median → for numerical data (best when outliers present)
imputer_median = SimpleImputer(strategy='median')
df['Age'] = imputer_median.fit_transform(df[['Age']])

# Mode (most frequent) → for categorical data
imputer_mode = SimpleImputer(strategy='most_frequent')
df['Embarked'] = imputer_mode.fit_transform(df[['Embarked']])

In [49]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked_0     0
Embarked_1     0
Sex_male       0
dtype: int64

In [27]:
# one hot encoder , less columns using pandas else we can do by sklearn also
df = pd.get_dummies(df, columns=['Sex'], drop_first=True)

# sklearn
#from sklearn.preprocessing import OneHotEncoder
#ohe = OneHotEncoder(sparse=False, drop='first')
#encoded = ohe.fit_transform(df[['Sex']])
# convert to DataFrame
#encoded_df = pd.DataFrame(encoded, columns=ohe.get_feature_names_out(['Sex']))
# merge back
#df = pd.concat([df, encoded_df], axis=1)
#df.drop('Sex', axis=1, inplace=True)

In [28]:
df.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_male
0,892,0,3,"Kelly, Mr. James",34.5,0,0,330911,7.8292,B57 B59 B63 B66,Q,True
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",47.0,1,0,363272,7.0000,NaN,S,False
2,894,0,2,"Myles, Mr. Thomas Francis",62.0,0,0,240276,9.6875,NaN,Q,True
3,895,0,3,"Wirz, Mr. Albert",27.0,0,0,315154,8.6625,NaN,S,True
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",22.0,1,1,3101298,12.2875,NaN,S,False

In [35]:
# used when categories have no order like A,B,C no specific order
# Label Encoder gives random values like 4,2,1,5 etc
# it gives int values
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Embarked'] = le.fit_transform(df['Embarked'])

In [34]:
df.head(30)

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_male
0,892,0,2,"Kelly, Mr. James",34.5,0,0,330911,7.8292,B57 B59 B63 B66,1,True
1,893,1,2,"Wilkes, Mrs. James (Ellen Needs)",47.0,1,0,363272,7.0000,NaN,2,False
2,894,0,1,"Myles, Mr. Thomas Francis",62.0,0,0,240276,9.6875,NaN,1,True
3,895,0,2,"Wirz, Mr. Albert",27.0,0,0,315154,8.6625,NaN,2,True
4,896,1,2,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",22.0,1,1,3101298,12.2875,NaN,2,False
5,897,0,2,"Svensson, Mr. Johan Cervin",14.0,0,0,7538,9.2250,NaN,2,True
6,898,1,2,"Connolly, Miss. Kate",30.0,0,0,330972,7.6292,NaN,1,False
7,899,0,1,"Caldwell, Mr. Albert Francis",26.0,1,1,248738,29.0000,NaN,2,True
8,900,1,2,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",18.0,0,0,2657,7.2292,NaN,0,False
9,901,0,2,"Davies, Mr. John Samuel",21.0,2,0,A/4 48871,24.1500,NaN,2,True
10,902,0,2,"Ilieff, Mr. Ylio",27.0,0,0,349220,7.8958,NaN,2,True
11,903,0,0,"Jones, Mr. Charles Cresson",46.0,0,0,694,26.0000,NaN,2,True
12,904,1,0,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",23.0,1,0,21228,82.2667,B45,2,False
13,905,0,1,"Howard, Mr. Benjamin",63.0,1,0,24065,26.0000,NaN,2,True
14,906,1,0,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",47.0,1,0,W.E.P. 5734,61.1750,E31,2,False
15,907,1,1,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",24.0,1,0,SC/PARIS 2167,27.7208,NaN,0,False
16,908,0,1,"Keane, Mr. Daniel",35.0,0,0,233734,12.3500,NaN,1,True
17,909,0,2,"Assaf, Mr. Gerios",21.0,0,0,2692,7.2250,NaN,0,True
18,910,1,2,"Ilmakangas, Miss. Ida Livija",27.0,1,0,STON/O2. 3101270,7.9250,NaN,2,False
19,911,1,2,"Assaf Khalil, Mrs. Mariana (Miriam"")""",45.0,0,0,2696,7.2250,NaN,0,False
20,912,0,0,"Rothschild, Mr. Martin",55.0,1,0,PC 17603,59.4000,NaN,0,True
21,913,0,2,"Olsen, Master. Artur Karl",9.0,0,1,C 17368,3.1708,NaN,2,True
22,914,1,0,"Flegenheim, Mrs. Alfred (Antoinette)",27.0,0,0,PC 17598,31.6833,NaN,2,False
23,915,0,0,"Williams, Mr. Richard Norris II",21.0,0,1,PC 17597,61.3792,NaN,0,True
24,916,1,0,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",48.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,0,False
25,917,0,2,"Robins, Mr. Alexander A",50.0,1,0,A/5. 3337,14.5000,NaN,2,True
26,918,1,0,"Ostby, Miss. Helene Ragnhild",22.0,0,1,113509,61.9792,B36,0,False
27,919,0,2,"Daher, Mr. Shedid",22.5,0,0,2698,7.2250,NaN,0,True
28,920,0,0,"Brady, Mr. John Bertram",41.0,0,0,113054,30.5000,A21,2,True
29,921,0,2,"Samaan, Mr. Elias",27.0,2,0,2662,21.6792,NaN,0,True

In [37]:
# used when categories have no order like A,B,C specific order
# Label Encoder gives random values like 1,2,3 for small,medium,high etc
# it gives float value
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()
df[['Embarked']] = oe.fit_transform(df[['Embarked']])

In [38]:
df.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_male
0,892,0,2,"Kelly, Mr. James",34.5,0,0,330911,7.8292,B57 B59 B63 B66,1.0,True
1,893,1,2,"Wilkes, Mrs. James (Ellen Needs)",47.0,1,0,363272,7.0000,NaN,2.0,False
2,894,0,1,"Myles, Mr. Thomas Francis",62.0,0,0,240276,9.6875,NaN,1.0,True
3,895,0,2,"Wirz, Mr. Albert",27.0,0,0,315154,8.6625,NaN,2.0,True
4,896,1,2,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",22.0,1,1,3101298,12.2875,NaN,2.0,False

In [41]:
# used when label + binary number conversion
# it gives binary value
# binary encoder is not in sklearn, for this we need to install category_encoders
!pip install category_encoders
import category_encoders as ce

be = ce.BinaryEncoder(cols=['Embarked'])
df = be.fit_transform(df)

Collecting category_encoders
  Downloading category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.0.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.16.3)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2026.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.9.0->category_encoders) (26.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Downloading category_encoders-2.9.0-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.9/85.9 kB 3.8 MB/s eta 0:00:00
Installing collected packages: category_encoders
Successfully installed category_encoders-2.9.0

In [42]:
df.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_0,Embarked_1,Sex_male
0,892,0,2,"Kelly, Mr. James",34.5,0,0,330911,7.8292,B57 B59 B63 B66,0,1,True
1,893,1,2,"Wilkes, Mrs. James (Ellen Needs)",47.0,1,0,363272,7.0000,NaN,1,0,False
2,894,0,1,"Myles, Mr. Thomas Francis",62.0,0,0,240276,9.6875,NaN,0,1,True
3,895,0,2,"Wirz, Mr. Albert",27.0,0,0,315154,8.6625,NaN,1,0,True
4,896,1,2,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",22.0,1,1,3101298,12.2875,NaN,1,0,False

In [43]:
# used when frequency matters , more important , used in large datasets
df['Sex_male'] = df['Sex_male'].map(df['Sex_male'].value_counts())

In [44]:
df.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_0,Embarked_1,Sex_male
0,892,0,2,"Kelly, Mr. James",34.5,0,0,330911,7.8292,B57 B59 B63 B66,0,1,266
1,893,1,2,"Wilkes, Mrs. James (Ellen Needs)",47.0,1,0,363272,7.0000,NaN,1,0,152
2,894,0,1,"Myles, Mr. Thomas Francis",62.0,0,0,240276,9.6875,NaN,0,1,266
3,895,0,2,"Wirz, Mr. Albert",27.0,0,0,315154,8.6625,NaN,1,0,266
4,896,1,2,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",22.0,1,1,3101298,12.2875,NaN,1,0,152